- prisma/migrations/20250105163730_add_cascade_to_inquiry/migration.sql
- prisma/schema.prisma
- src/controllers/inquries.controller.ts
The bug occurred because when attempting to delete a listing, any inquiries associated with that listing caused a foreign key constraint issue. To address this, I updated the schema by adding an onDelete: cascade attribute to the Inquiry model. This ensures that whenever a listing is deleted, all related inquiries are automatically removed, resolving the issue.
> Resolved bug while delete listing error.

- src/controllers/admin.controller.ts
- src/db/seed.ts
- src/index.ts
- src/middlewares/admin.middleware.ts
- src/routes/admin.route.ts
- src/services/admin.service.ts
- src/services/auth.service.ts
> Admin Routes Added

- src/crons/listingApprovalCron.ts
- src/services/firebase.service.ts
> Reduced DB Usage of Notifications

- src/controllers/notifications.controller.ts
- src/routes/notifications.route.ts
- src/services/notifications.service.ts
> Delete Notifications Api

- src/controllers/admin.controller.ts
- src/services/admin.service.ts
Search Accross pagination in Listings page added,
Email id added .
> Feat: Search Added

- src/db/seed.ts
Added Developers , brokerages ,and projects data in  seed! 
-   [ x ] I have tested these changes locally.
-   [ x ] I have added appropriate documentation or comments where necessary.
> feat: added developers data in seed

- src/controllers/dashboard.controller.ts
- src/routes/dashboard.route.ts
- src/services/dashboard.service.ts
> fix: dashboard stats auth issue fix

- package-lock.json
- package.json
- prisma/migrations/20250712164720_edited_company_model_and_added_admin_user_model/migration.sql
- prisma/schema.prisma
- src/controllers/adminusercontroller.ts
- src/controllers/company.controller.ts
- src/db/seed.ts
- src/index.ts
- src/routes/adminuser.routes.ts
- src/routes/company.route.ts
- src/services/adminuser.service.ts
- src/services/brokerage.service.ts
- src/services/developer.service.ts
> feat: company schema changed & auth apis added

- src/controllers/adminusercontroller.ts
- src/routes/adminuser.routes.ts
- src/services/adminuser.service.ts
> Feat: Change password api & Edit developers api added

- src/controllers/admin-user.controller.ts
- src/routes/admin-user.routes.ts
- src/services/admin-user.service.ts
> feat: getcompanyById api added

- src/controllers/company.controller.ts
- src/routes/admin-user.routes.ts
- src/routes/company.route.ts
- src/schema/createProjectschema.ts
- src/schema/editDeveloperSchema.ts
- src/services/brokerage.service.ts
- src/services/company.service.ts
1. Validation added in editDevelopers API
2. Validation added in CreateProject API
3. fetch Brokers by CompanyId API Added"
4. Listing count of developers Added.
> Validation , ListingsCount and fetchbrokers Api Added

- src/controllers/brokerage.controller.ts
- src/services/brokerage.service.ts
-   [x] I have tested these changes locally.
> Fix: added listings count Service

- prisma/migrations/20250719094005_company_post_schemaadded/migration.sql
- prisma/schema.prisma
- src/controllers/admin-user.controller.ts
- src/controllers/company.controller.ts
- src/routes/admin-user.routes.ts
- src/routes/company.route.ts
- src/services/admin-user.service.ts
- src/services/company.service.ts
1. Create a Companypost api added in the admin user
2. Edit the CompanyPost API added in the admin user
3. Get the company Post API added in the company Routes
4. Get companyPostbyId API added in company Routes
> feat: CompanyPost API's added

- prisma/migrations/20250724100913_added_adminuser_in_jobs_model/migration.sql
- prisma/schema.prisma
- src/controllers/admin-user.controller.ts
- src/routes/admin-user.routes.ts
- src/schema/job.schema.ts
- src/services/admin-user.service.ts
- src/services/job.service.ts
Three APIs added
1. Create Jobs in the admin user
2. Get jobs by userid
3. get jobs details by jobid
> feat: Create Jobs api Added

- src/controllers/job.controller.ts
- src/services/job.service.ts
Added  Applied in get jobs by id. 
> feat: added applied in get jobsby id

- prisma/migrations/20250806121355_updated_changes_for_admin/migration.sql
- src/db/seed.ts
> fix: server issues

- src/controllers/admin-user.controller.ts
- src/routes/admin-user.routes.ts
- src/routes/job.route.ts
- src/services/admin-user.service.ts
- src/services/job.service.ts
- src/utils/verifyToken.ts
> feat: updated applied jobs response

- prisma/migrations/20250810175051_added_sponsored_listings/migration.sql
- prisma/schema.prisma
- src/services/job.service.ts
> feat: added is_sponsored for jobs

- src/services/brokerage.service.ts
- src/services/brokers.service.ts
> feat: listings count added

- src/controllers/listings.controller.ts
- src/services/listings.service.ts
Pagination added in featured api listings.
> feat: pagination added in featured listings api

- src/controllers/listings.controller.ts
- src/middlewares/auth.middleware.ts
- src/services/listings.service.ts
> Listingsget

- src/controllers/brokers.controller.ts
- src/data/merged_property_data.json
- src/routes/brokers.route.ts
- src/utils/roiReport.ts
> feat: added property json data for roi

- src/data/merged_property_data.json
- src/utils/roiReport.ts
> feat: added roi report methods

- src/services/listings.service.ts
> feat: rounded values

- src/services/developer.service.ts
> feat: developers response updated

- src/utils/roiReport.ts
> fix: update roi graph from absolute profit to percentages

- src/services/listings.service.ts
- src/utils/roiReport.ts
> fix: add min price check

- src/services/listings.service.ts
- src/utils/roiReport.ts
> fix: add user preferences for ROI calculations

- src/utils/roiReport.ts
> Add ROI report utility

- src/controllers/listings.controller.ts
- src/routes/listings.route.ts
- src/services/listings.service.ts
- src/utils/roiReport.ts
> feat: add support for generating AI report

- src/services/job.service.ts
> fix: update jobs service

- src/services/job.service.ts
> fix: response fix for get all jobs

- src/data/property-data-v3.ts
> fix: add new property data file

- src/utils/roiReport.ts
> fix: add default break even year and log errors

- src/data/property-data-v4.ts
> Fix break even

- src/controllers/listings.controller.ts
- src/routes/listings.route.ts
- src/services/listings.service.ts
- src/utils/roiReport.ts
> fix: update roi logic for rentals and update roi report schema

- src/services/listings.service.ts
- src/utils/roiReport.ts
> fix: add market pulse data

- src/controllers/project.controller.ts
- src/services/project.service.ts
> feat: search updated

- prisma/migrations/20250906164604_add_views_to_project/migration.sql
- prisma/schema.prisma
- src/controllers/project.controller.ts
- src/routes/project.route.ts
- src/services/project.service.ts
> feat: featured projects api added

- src/services/project.service.ts
> fix : response updated

- src/controllers/project.controller.ts
- src/routes/project.route.ts
- src/services/project.service.ts
> feat: floor Plans api udated

- src/controllers/project.controller.ts
- src/routes/project.route.ts
- src/services/project.service.ts
> feat: floorplan and project details updated

- src/services/project.service.ts
- src/utils/roiReport.ts
> fix: roi related issues

- src/services/developer.service.ts
> feat: project count fixed

- src/services/listings.service.ts
- src/services/project.service.ts
> Feat: Roi report, ai-report changes for rentlogic & FLoorPlan

- src/services/listings.service.ts
- src/services/project.service.ts
This reverts commit de80c6ffdbecc6047e974e6fdffdb7209e59c7fd.
[Add any additional notes or context that may be helpful for …
> Revert "Feat: Roi report, ai-report changes for rentlogic & FLoorPlan"

- src/controllers/project.controller.ts
- src/routes/project.route.ts
- src/services/project.service.ts
> feat: Get Project by Name api added

- src/services/project.service.ts
> feat: add payment-plan and location

- src/services/project.service.ts
> fix: update project ai ppt api structure

- src/controllers/listings.controller.ts
- src/data/property-data-v5.ts
- src/routes/listings.route.ts
- src/services/listings.service.ts
- src/utils/roiReport-v2.ts
> feat: update utils to use roi instead of rent

- src/utils/roiReport-v2.ts
> fix: short term break even year calculation

- src/apps/admin/project/project.controller.ts
- src/apps/admin/project/project.service.ts
- src/schema/project.schema.ts
> feat: adminpanel forms fixes: payment strucuture, bedrooms

- src/services/developer.service.ts
> fix: developer by id issue fixed
